---
# NTP role handlers

- name: Restart chrony
  ansible.builtin.systemd:
    name: chrony
    state: restarted
  when: ansible_virtualization_type | default('') != 'docker'
  listen: Restart chrony
