---
# NTP role handlers

- name: Restart systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted
  when: ansible_virtualization_type | default('') != 'docker'
  listen: Restart systemd-timesyncd
